module.exports = {
  env: {
    es2021: true,
    browser: true,
    jquery: true,
  },
  globals: {
    sap: true,
    jQuery: true,
  },
  rules: {
    "array-callback-return": "error",
    "arrow-spacing": "warn",
    "block-scoped-var": "error",
    "brace-style": "warn",
    camelcase: "warn",
    "comma-spacing": ["warn", { before: false, after: true }],
    "comma-style": "warn",
    "consistent-return": "error",
    "default-case": "warn",
    "default-case-last": "error",
    "default-param-last": "error",
    eqeqeq: "error",
    "func-name-matching": "error",
    "grouped-accessor-pairs": "warn",
    "id-length": ["warn", { max: 30 }],
    "key-spacing": ["warn", { beforeColon: false }],
    "keyword-spacing": "error",
    "max-depth": ["error", 4],
    "max-nested-callbacks": ["error", 3],
    "max-params": ["error", 8],
    "max-statements": ["warn", 24, { ignoreTopLevelFunctions: true }],
    "new-cap": "warn",
    "no-array-constructor": "error",
    "no-await-in-loop": "off",
    "no-caller": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": "error",
    "no-eval": "error",
    "no-else-return": "warn",
    "no-extra-semi": "error",
    "no-implied-eval": "error",
    "no-irregular-whitespace": "error",
    "no-lonely-if": "warn",
    "no-loop-func": "error",
    "no-mixed-operators": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-wrappers": "error",
    "no-promise-executor-return": "error",
    "no-prototype-builtins": "error",
    "no-self-compare": "error",
    "no-template-curly-in-string": "warn",
    "no-throw-literal": "error",
    "no-undef": "error",
    "no-unreachable-loop": "error",
    "no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      },
    ],
    "no-useless-concat": "error",
    "no-var": "error",
    "no-warning-comments": "warn",
    "prefer-const": "error",
    "prefer-object-spread": "error",
    "prefer-template": "warn",
    radix: "error",
    "require-atomic-updates": "error",
    semi: ["error", "always"],
    "space-unary-ops": "error",
    "template-curly-spacing": "warn",
  },
};
